import {chromium} from 'playwright';
import {serve} from '../server.mjs';
const {server, url} = await serve();
const b = await chromium.launch();
const p = await b.newPage({viewport: {width: 1440, height: 900}});
const errs = []; p.on('pageerror', e => errs.push(e.message)); p.on('requestfailed', r => errs.push('fail ' + r.url())); p.on('response', r => { if (r.status() >= 400) errs.push(r.status() + ' ' + r.url()); });
p.on('request', r => { if (!r.url().startsWith(url)) errs.push('external ' + r.url()); });
const R = sel => p.evaluate(s => { const e = document.querySelector(s); if (!e) return null; const r = e.getBoundingClientRect(); return [Math.round(r.x), Math.round(r.y), Math.round(r.width), Math.round(r.height)]; }, sel);
await p.goto(url + '/site/index.html'); await p.evaluate(() => window.__siteReady); await p.waitForTimeout(800);
const out = {};
for (const s of ['.brand', '.nav-tabs [data-tab=code]', '.nav-tabs [data-tab=prompt]', '.nav-tabs [data-tab=skill]', '#typeDescription', '.search', '#languageToggle', '#uploadEntry', '.category-tab[data-category=product]', '.card:nth-child(1) .card-media', '.card:nth-child(2) .card-media', '.card:nth-child(3) .card-media']) out[s] = await R(s);
out.desc = await p.evaluate(() => document.getElementById('typeDescription').textContent);
await p.screenshot({path: 'evidence/site-offline.png'});
await p.click('.card:nth-child(1) .card-media'); await p.waitForTimeout(300);
for (const s of ['.modal', '.modal-video video', '#modalTitle', '#modalCopy', '#modalCopyBlock', '.copy-label']) out['modal ' + s] = await R(s);
await p.click('#modalCopy'); await p.waitForTimeout(200);
out.toast = [await R('#toast'), await p.evaluate(() => document.getElementById('toast').className + ' ' + document.getElementById('toast').textContent)];
out.copyText = await p.evaluate(() => document.getElementById('modalCopyBlock').textContent);
await p.screenshot({path: 'evidence/site-offline-modal.png'});
console.log(JSON.stringify(out, null, 1)); console.log('ERRORS', errs);
await b.close(); server.close();
